apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: han-coursegenerator
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/ReinoutWW/gitops-argocd-projects
    targetRevision: HEAD
    path: projects/han-coursegenerator
  destination:
    server: https://kubernetes.default.svc
    namespace: han-coursegenerator

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true