apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-blockchain-deployment
spec:
  selector:
    matchLabels:
      app: grade-blockchain
  replicas: 1
  template:
    metadata:
      labels:
        app: grade-blockchain
    spec:
      containers:
      - name: grade-blockchain
        image: reinoutw/han-grade-blockchain:1.9.0
        ports:
        - containerPort: 8080