apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursegen-deployment
spec:
  selector:
    matchLabels:
      app: coursegen
  replicas: 1
  template:
    metadata:
      labels:
        app: coursegen
    spec:
      containers:
      - name: coursegen
        image: reinoutw/han-coursegenerator-teacher-portal:1.3.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coursegen-nodeport-service
spec:
  type: NodePort
  selector:
    app: coursegen
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008