apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server  # <-- must match argocd-server pod labels
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 8083
      protocol: TCP
      nodePort: 30443
