resources:
  requests:
    memory: 8Gi
    cpu: "1000m"
  limits:
    memory: 10Gi
    cpu: "2000m"
    
persistence:
  labels: {}
  annotations: {}
  ## specify an alternative volume to be mounted to /data instead of datadir.
  # altDataVolumeName: ""
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  dataDir:
    # Set this to false if you don't care to persist state between restarts.
    enabled: false
    Size: 10Gi
    storageClass: "nfs-csi"
    accessModes:
      - ReadWriteOnce
    # existingClaim: nil
    ## specify a subpath in the volume where the data is. Useful when sharing volumes with other apps.
    # subPath: /path/to/dataDir
    
  
minecraftServer:
  eula: "TRUE"
  serviceType: NodePort
  nodePort: 30100
  
  